image: node:18

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm -g i npm@9

chromatic:
  stage: test
  tags:
    - test
  script:
    - npm ci
    - npm run chromatic
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
